version: '3.8'
services:
  web:
    image: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./plugins:/var/www/html/wp-content/plugins/
      - ./themes:/var/www/html/wp-content/themes/
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wp
      WORDPRESS_DEBUG: 1
    depends_on:
      - db
    networks:
      - wpnet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - wpnet
  db:
    image: mariadb:10.5
    restart: always
    ports:
      - 6603:3306
    volumes:
      - wpdbvol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wpnet
volumes:
  wordpress: {}
  wpdbvol: {}
networks:
  wpnet: {}
