version: '3.8'
services:
  wp:
    image: wordpress:${WP_TAG:-latest}
    restart: always
    volumes:
      - wordpress:/var/www/html
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./plugins:/var/www/html/wp-content/plugins/
      - ./themes:/var/www/html/wp-content/themes/
    ports:
      - ${WP_PORT:-8080}:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: ${WPDB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${WPDB_PASS:-examplepass}
      WORDPRESS_DB_NAME: ${WPDB_NAME:-exampledb}
      WORDPRESS_TABLE_PREFIX: ${WPDB_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DISABLE_FATAL_ERROR_HANDLER', true);
        define('SCRIPT_DEBUG', true);
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('WP_DEVELOPMENT_MODE', 'all');
    depends_on:
      - wpdb
    networks:
      - wpnet
  wpcli:
    image: wordpress:${WPCLI_TAG:-cli}
    restart: always
    user: 33:33
    volumes_from:
      - wp
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: ${WPDB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${WPDB_PASS:-examplepass}
      WORDPRESS_DB_NAME: ${WPDB_NAME:-exampledb}
      WORDPRESS_TABLE_PREFIX: ${WPDB_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DISABLE_FATAL_ERROR_HANDLER', true);
        define('SCRIPT_DEBUG', true);
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('WP_DEVELOPMENT_MODE', 'all');
    depends_on:
      - wp
      - wpdb
    networks:
      - wpnet
    stdin_open: true
    tty: true
    working_dir: /var/www/html
  adminer:
    image: adminer:${ADMINER_TAG:-latest}
    restart: always
    ports:
      - ${ADMINER_PORT:-8081}:8080
    depends_on:
      - wpdb
    networks:
      - wpnet
  wpdb:
    image: mariadb:${MARIADB_TAG:-10.5}
    restart: always
    ports:
      - ${WPDB_PORT:-6603}:3306
    volumes:
      - wpdbvol:/var/lib/mariadb
    environment:
      MYSQL_DATABASE: ${WPDB_NAME:-exampledb}
      MYSQL_USER: ${WPDB_USER:-exampleuser}
      MYSQL_PASSWORD: ${WPDB_PASS:-examplepass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wpnet
volumes:
  wordpress: {}
  wpdbvol: {}
networks:
  wpnet: {}
